#!groovy

stage ('Production') {
    build 'build-chocolate'
}

stage ('Acceptance Tests') {
    build 'test-chocolate'
}

stage ('Packaging') {
    node ('Tools:packaging') {
        // get configuration from config job and inject as groovy vars
        step([$class: 'CopyArtifact', fingerprintArtifacts: true, projectName: 'configure-chocolate', selector: [$class: 'StatusBuildSelector', stable: false]])
        load 'config.groovy'
        echo "Wrapping the chocolate bar now into ${noAluminium ? 'plastic' : 'aluminium'} foil"
        echo 'Wrapping the chocolate bar now into paper'
        echo "Packaging $boxSize chocolate bars into a box"
    }
}

stage ('Manual Approval') {
    if (env.BUILD_NUMBER.toInteger() % 10 == 0) {
        timeout(time: 1, unit: 'HOURS') {
        input message: 'Is this chocolate packed OK and tasty?'
        }
    }
}

stage ('Delivery') {
    node ('Tools:delivery') {
        echo "Delivering boxes to $hauler..."
    }
}
